---
version: '3.7'
services:

  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./cassandra/data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s
      timeout: 5s
      retries: 10





    
    
    
